services:
  postgres:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=jlDbNJ8hVlg7Aq65npn2owIfnewARqf1SIWHZfnEkpkTj2ZrSguZfCm8cUL4GD46
      - POSTGRES_USER=byf-writer
      - POSTGRES_DB=byf
  byf:
    image: adrgor/byf-backend:latest
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"